package taskstore

const COLUMN_ALIAS = "alias"
const COLUMN_ATTEMPTS = "attempts"
const COLUMN_COMPLETED_AT = "completed_at"
const COLUMN_CREATED_AT = "created_at"
const COLUMN_DELETED_AT = "deleted_at"
const COLUMN_DETAILS = "details"
const COLUMN_ID = "id"
const COLUMN_DESCRIPTION = "description"
const COLUMN_MEMO = "memo"
const COLUMN_PARAMETERS = "parameters"
const COLUMN_OUTPUT = "output"
const COLUMN_STARTED_AT = "started_at"
const COLUMN_STATUS = "status"
const COLUMN_TASK_ID = "task_id"
const COLUMN_TITLE = "title"
const COLUMN_UPDATED_AT = "updated_at"

const ASC = "asc"
const DESC = "desc"
